apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: rag-chatbot 
  janus-idp.io/tekton: rag-chatbot
  backstage.io/kubernetes-id: rag-chatbot
  backstage.io/kubernetes-namespace: rhdh-app 
  app.kubernetes.io/part-of: rag-chatbot
resources: 
- application-dev.yaml