apiVersion: batch/v1
kind: Job
metadata:
  name: dsp-clone-job-rag-chatbot-gitops
spec:  
  template:         
    metadata:
      name: dsp-clone-job-rag-chatbot-gitops
    spec:  
      serviceAccountName: rag-chatbot-dsp-job
      containers:
      - name: initialize-dsp
        image: quay.io/redhat-ai-dev/utils:latest
        command:
        - /bin/bash
        - -c
        - |
          NS=$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace)
          oc wait -l statefulset=rag-chatbot-notebook --for=condition=ready pod --timeout=300s
          oc exec  StatefulSet/rag-chatbot-notebook -- git clone https://github.com/gabemontero-appstudio-test-org/rag-chatbot
      restartPolicy: Never